# Docker file for prototype development with CLion, Pycharm & Webstorm
#
# Build and run:
#   LINK SSH:
#   ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:2222"
#
#   Latest:
#   docker build -t dev/development-env -f dockerfile .
#   docker run -d --cap-add sys_ptrace -p127.0.0.1:2224:22 -p8890:8890 -p8889:8889 --name dev en/dev-base:0.1
#
# Access the image remotely:
#   docker exec -it <container_name> zsh
#
# stop:
#   docker stop dev
#
# ssh credentials (test user):
#   user@password
#


FROM ubuntu:20.04

RUN apt-get update

RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y ssh \
      build-essential \
      gcc \
      g++ \
      gdb \
      git \
      clang \
      cmake \
      rsync \
      tar \
      screen \
      zsh \
      vim \
      python3 \
      python3-pip \
      libgtest-dev \
      zlib1g-dev \
      libturbojpeg \
      libssl-dev \
      libuv1-dev \
      libsm6 \
      libxext6 \
      libxrender-dev \
  && apt-get clean
  
# NOTE: libsm6 libxext6 libxrender-dev are needed for cv2 to be imported correctly :(

# to complete gtest install, need to go
# to gtest folder, run cmake, make and
# cp the files from lib to /usr/lib

RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
  ) > /etc/ssh/sshd_config_dev \
  && mkdir /run/sshd

RUN useradd -m user \
  && yes password | passwd user


# set up zsh:
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true

# add prompt notice that you are in docker/screen:
Run echo "if [[ \$TERM == screen ]]; then \n\tPROMPT=\"%B%F{red}(DOCKER[%b%f%B%F{green}SCREEN%b%f%B%F{red}])%b%f \$PROMPT\" \nelse\n\tPROMPT=\"%B%F{red}(DOCKER)%b%f \$PROMPT \" \nfi" >> /root/.zshrc


# Screen shell link:
RUN echo "shell \"/usr/bin/zsh\"" >> /etc/screenrc

# update pip:

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_dev"]
